### ISSUE TITLE
Server Error: Unauthorized

### ISSUE THREAD

**Issue by itamair** [chapter-three/next-drupal#15] opened 2021-08-13 22:18 UTC
As a follow up of this https://github.com/chapter-three/next-drupal/issues/14 resolution, I now hit this error on http://localhost:3000

<img width="1127" alt="Screenshot 2021-08-14 at 00 17 36" src="https://user-images.githubusercontent.com/1429859/129423359-6981d511-615f-4e46-87cf-c32da2a02dc4.png">

**Comment by itamair** [comment] 2021-08-13 22:18
Any idea of how to solve this?

**Comment by arshad** [comment] 2021-08-14 00:27
Can you verify if the DRUPAL_CLIENT_ID and DRUPAL_CLIENT_SECRET are correct?

**Comment by arshad** [comment] 2021-08-14 00:29
Any errors in the Drupal logs?

**Comment by itamair** [comment] 2021-08-15 10:19
I have setup only 1 user, that is the default one, with the following parameters:
UUID: 87d125fd-2f98-43e7-9ff3-18d1755f8037
New Secret: secret 
(last one is stored as Hash in the DB, of course).

<img width="1332" alt="Screenshot 2021-08-15 at 12 10 18" src="https://user-images.githubusercontent.com/1429859/129475102-3759a6c3-c482-4cac-aa4d-ef33cb4d5423.png">

And I am using the following data in the env.local file (of the NextJs client app):

```
NEXT_PUBLIC_DRUPAL_BASE_URL=https://drupal-site.ddev.site
NEXT_IMAGE_DOMAIN=drupal-site.ddev.site
DRUPAL_SITE_ID=1ccd4bc4-bbc6-4c19-a816-c7d100feff02
DRUPAL_FRONT_PAGE=/node/6
DRUPAL_PREVIEW_SECRET=secret
DRUPAL_CLIENT_ID=87d125fd-2f98-43e7-9ff3-18d1755f8037
DRUPAL_CLIENT_SECRET=secret

NODE_TLS_REJECT_UNAUTHORIZED=0
```

I can see the following error log in the Drupal site once I try to run the http://localhost:3000:

`League\OAuth2\Server\Exception\OAuthServerException: Client authentication failed in League\OAuth2\Server\Exception\OAuthServerException::invalidClient() (line 154 of /var/www/html/vendor/league/oauth2-server/src/Exception/OAuthServerException.php).`

I am not super expert of the simple_oauth module, with JSONAPI, but I am wondering that the miss of any generated token could mean something here ... 

<img width="1326" alt="Screenshot 2021-08-15 at 12 15 07" src="https://user-images.githubusercontent.com/1429859/129475107-e4c84856-624e-41d0-985f-0223794c9131.png">

Simple OAuth Settings looks like the followings (and I can see the Generated Keys in my "sites/default/files/private" folder ... 

<img width="1328" alt="Screenshot 2021-08-15 at 12 18 52" src="https://user-images.githubusercontent.com/1429859/129475180-24f52229-397e-4c79-b63d-85b9bbee7c3b.png">

**Comment by arshad** [comment] 2021-08-15 16:04
hmm, did you configure a user for the client?

<img width="701" alt="" src="https://user-images.githubusercontent.com/124599/129484807-f9997dc8-47a5-478a-9dda-26cd16f7d534.png">

**Comment by itamair** [comment] 2021-08-16 09:08
Yes I did ... the itamair user is administrator and also with "Next site previewer" role ... 

<img width="1012" alt="Screenshot 2021-08-16 at 11 06 37" src="https://user-images.githubusercontent.com/1429859/129539506-81522887-9ff8-44e9-ae0f-73f9ae16bd32.png">

<img width="948" alt="Screenshot 2021-08-16 at 11 07 14" src="https://user-images.githubusercontent.com/1429859/129539514-5e09d632-c28f-402b-beec-eed91fdc595d.png">

**Comment by itamair** [comment] 2021-08-16 09:38
I am concerned there is something wrong with the Oauth module settings (and still don't get what as I am not now able to xdebug it).
But when I visit this GET Route: /oauth/debug
I receive the following outcome: 

`{"message":"The used authentication method is not allowed on this route."}`

Should something be properly set on the Rest Resources (/admin/config/services/rest) or somewhere else on JSONAPI that is not mentioned in the Quickstart guide???

**Comment by itamair** [comment] 2021-08-16 10:21
Worth to also mention (may be is relevant to this issue) that still no oauth2 token entity has been created in my Drupal BE, and I don't know how it should be created ... 

<img width="1207" alt="Screenshot 2021-08-16 at 12 19 51" src="https://user-images.githubusercontent.com/1429859/129549098-9320b905-939e-4cb6-a258-5b91efabe5fd.png">

**Comment by itamair** [comment] 2021-08-16 20:49
Ah! Finally I was able to make (almost) all this working ... 
I was totally missing the proper setup of the Oauth module and generation of access tokens ... 
Basically I had to properly follow the Quick demo (Password Grant) section of the [OAuth2 module](https://www.drupal.org/project/simple_oauth) and some of its Video Tutorials.

For sake of sharing my findings, after creating a consumer Client Application, it is crucial properly generate the Access Tokens with some POST request of the following type: 

```
curl -X "POST" "https://drupal-site.ddev.site/oauth/token" \
     -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' \
     --data-urlencode "grant_type=password" \
     --data-urlencode "client_id=[client_id]" \
     --data-urlencode "client_secret=[client_secret]" \
     --data-urlencode "scope=[scope]" \
     --data-urlencode "username=[username]" \
     --data-urlencode "password=[password]"
```

I thing reference to all this Oauth module setup (and generation of access tokens) should be mentioned in the Quickstart guide & repo documentation, for all those (like me) are not expert of the Drupal Oauth module.

**Comment by arshad** [comment] 2021-08-17 06:23
Thanks for the update and the fix @itamair. I'll update the documentation.

If you have any other suggestions on how we can improve the onboarding/setup process, you can ping me.

**Comment by testevez** [comment] 2021-08-17 22:06
I have the same issue. I used this thread to get a proper response via Postman. However, the issue remains. I feel like the issue with with the keys, but I am not sure how to fix it. I have tried generating the keys in admin/config/people/simple_oauth as well as via CLI as per the instructions in https://www.drupal.org/project/simple_oauth, neither results in a fix for me. I will be watching this thread for updates, thanks.

**Comment by Juc1** [comment] 2021-09-17 12:34
> Thanks for the update and the fix @itamair. I'll update the documentation.

Hi all were the docs https://next-drupal.org/docs/quick-start updated or do I need to do extra OAuth2 stuff as mentioned by @itamair ?

**Comment by shadcn** [comment] 2021-09-17 14:28
@Juc1 I've not updated the docs yet. Are you facing the same issues?

**Comment by Juc1** [comment] 2021-09-17 14:59
@shadcn yes I am getting "Error:Unauthorised" like itamair's screenshot at the top of this issue.

**Comment by janoka** [comment] 2021-09-22 19:23
Hi Guys, 
I've the same error:
![CleanShot 2021-09-22 at 21 18 38](https://user-images.githubusercontent.com/2426494/134407816-adf31997-fc39-4f42-ace5-ee23a112c709.png)

I also tested with Postman, and Drupal had generated the Bearer access_token.

It seems to me the client tries to use _Basic authentication_, but _Oauth2_ accept `username` and `passowrd` only in `body`.

**Comment by shadcn** [comment] 2021-10-04 13:31
I noticed this issue when I created a client/consumer before generating keys (private and public) keys.

I fixed this by deleting the consumer and recreating it again.

**Comment by KojoEnch** [comment] 2021-10-30 17:59
Had the same issue, tried all of the above solutions : generated token with curl, deleted and recreated consumer...

**I'm using ddev** for Drupal and I could solve it after I filled NEXT_PUBLIC_DRUPAL_BASE_URL and NEXT_IMAGE_DOMAIN  values **with the http url** (eg _http://myblog.site:8008_) instead of the https one (_https://myblog.ddev.site _). 

By the way, I stumble then on **Not found** errors, whether on the homepage or after creating some content. This might be addressed in another issue though. I'll double check the docs and code before. Thanks for this promising repo and the amazing work done !

**Comment by shadcn** [comment] 2021-10-31 15:56
> ... I suggest that you mention in the quick start guide, to enable Json Api module, and any other required dependencies.

The Next.js JSON:API module list JSON:API module as a dependency. I'll update the docs. 

@KojoEnch I've been wanting to try ddev for a while. Are you running both Drupal and the Next.js site on the same setup? Mind sharing your config?

Thanks for the feedback. Appreciate the feedback.

**Comment by KojoEnch** [comment] 2021-11-01 11:54
Well, I just use default config. I use ddev most of the time now for a while and recommend it, since it provides a full containerized dev env for each project in less than a minute. 

So I made a new fresh install following your quick start guide this morning, and I can confirm that **for ddev users, the install problem comes from the https**. I think node complains for self signed certificates, I've had the same problem in a previous hand made drupal + next config. There are ways to setup that but this is beyond the scope of that issue. So for a clean install with ddev :

-  [install ddev globally](https://ddev.readthedocs.io/en/stable/#installation)
- `composer create-project drupal/recommended-project drupal-site`
- `cd drupal-site && ddev config --http-port=8008 ` (any unused custom port to avoid conflicts)
- `ddev describe` : check all the urls provided to access the project, as well as mailhog, phpmyadmin ... and pick the http one for next config
- go to the https one and install the site.
- `composer require drush/drush`
- `composer require drupal/next:1.0.0-beta6`
- `ddev exec drush en next next_jsonapi -y` (run drush from inside the container)

Then follow the install from https://next-drupal.org/docs/quick-start#4-create-site until .env.local step and fill in NEXT_PUBLIC_DRUPAL_BASE_URL with ddev http url : `NEXT_PUBLIC_DRUPAL_BASE_URL=http://drupal-site.ddev.site:8001`

No extra needs, the tokens are properly set when we access front site, and front page is accessible without error.

**Comment by shadcn** [comment] 2021-11-01 13:05
@KojoEnch Thank you. I'll add this to the documentation.

**Comment by Peppe87** [comment] 2021-12-14 15:06
I'm starting to test this tool on Drupal 9.3. I'm also using ddev.

The first time I had to do a POST request - [https://github.com/chapter-three/next-drupal/issues/15#issuecomment-899808977](as itamair said in a post above). Subsequently, the next.js site started to work.

It was not necessary for me to use the http url. In other words, `NEXT_PUBLIC_DRUPAL_BASE_URL=https://drupal9-site.ddev.site` works fine for me.

**Comment by darrenoh** [comment] 2021-12-16 00:51
I'm seeing new tokens being created every time the front end refreshes. Also seeing this error in the Drupal log:

> ArgumentCountError: Too few arguments to function Drupal\simple_oauth\Entities\AccessTokenEntity::convertToJWT(), 0 passed in /var/www/html/vendor/league/oauth2-server/src/Entities/Traits/AccessTokenTrait.php on line 78 and exactly 1 expected in Drupal\simple_oauth\Entities\AccessTokenEntity->convertToJWT() (line 21 of /var/www/html/web/modules/contrib/simple_oauth/src/Entities/AccessTokenEntity.php)

**Comment by shadcn** [comment] 2021-12-16 07:24
@darrenoh this error is a known issue in the Simple OAuth module. See:

- https://www.drupal.org/project/simple_oauth/issues/3197616
- https://www.drupal.org/project/simple_oauth/issues/3230707

Can you create a separate issue to track the token generation issue please?

Thank you

**Comment by crackayus09** [comment] 2022-02-06 14:49
I faced the same issue. Resolved it by installing `Next.js JSON:API` module. I think they forgot in the doc to mention about this.

**Comment by shakilahmad46** [comment] 2022-03-24 19:36
I followed all the above comments and the quick start guide but still, the issue remains.
![Uploading Screen Shot 2022-03-25 at 12.34.50 AM.png…]()

**Comment by simon-olsen** [comment] 2022-03-29 09:14
> Had the same issue and I recreated the Consumer, regenerated the keys and it started working for me.

Did you try deleting and [recreating the consumer](https://github.com/chapter-three/next-drupal/issues/15#issuecomment-939373902)?

**Comment by theodorosploumis** [comment] 2022-03-31 09:19
I had the same issue as above. 
For me the problem was the **usage of `http` instead of `https`**. The Drupal site was using `https` and the call with `http` was only redirected to `https` with a GET request. So POST requests to `http` were not allowed! 

The Drupal error log was:

```
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "GET /oauth/token": Method Not Allowed (Allow: POST) in 
Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest() (line 140 of /vendor/symfony/http-kernel/EventListener/RouterListener.php).
``` 

I also think that the tool from https://github.com/shadcn/next-drupal-debug should be included on the main repository as a tool...

**Comment by shadcn** [comment] 2022-07-03 10:08
@itamair I'm going to close this as done/stale. Feel free to reopen if not. Thank you.

**Closed by shadcn** 2022-07-03 10:08 UTC

**Comment by queenvictoria** [comment] 2023-01-05 04:17
I appreciate that this is closed. However just adding one more scenario that causes this error that I solved using this thread (the `curl` process above).

My Drupal salt was too short. The error message I received eventually was:

```json
{
     "error": "server_error",
     "error_description": "The authorization server encountered an unexpected condition which prevented it from fulfilling the request: Hash salt must be at least 32 characters long.",
     "message": "The authorization server encountered an unexpected condition which prevented it from fulfilling the request: Hash salt must be at least 32 characters long."
}
```
