### ISSUE TITLE
when using ISR NEXT won't allow to reuse old alias without rebuilding the entire app

### ISSUE THREAD

**Issue by je34429** [chapter-three/next-drupal#171] opened 2022-04-22 16:44 UTC
I have an app built in with ISR (getStaticProps + getStaticPaths and revalidate) it uses the [slug] method to render all contents so my pages directory is quite simple:

index.js and [slug].js

everything works fine until I disable a node, say I have a node called foo in /foo and I rename its alias to /foo2, I will be able to see the node at /foo2 after a few seconds depending on the revalidation time, but when I try to rename /foo2 to /foo again it won't work anymore instead it will show a permanent 404.

A curious fact is that the html of foo.html and its foo.json will remain all the time in the server/pages folder, another curious fact is that if I access the node using a capital letter anywhere on the slug string it will load with no problems: for example /FOo will render the contents on /foo,  but for some reason it seems like the router will put the /foo path in some kind of permanent black list of 404 destinations and won't let drupal to reuse the old alias until the front end layer gets rebuild again.

I wonder if there is any workaround to reuse the old alias again somehow at runtime without rebuilding the entire front layer again.

thanks in advance for any help or advice

**Comment by shadcn** [comment] 2022-04-22 17:58
Interesting. Do you have on-demand revalidation on for this content type? It looks like when revalidation is called (hook_entity_update), it does not have context of the path alias changed and this is messing the cache on the next.js side.

I'll try to reproduce this and get back to you.

**Comment by je34429** [comment] 2022-04-22 18:38
Hi, thanks for your quick answer, yeah my fetching flow is as follows:
```

export async function getStaticProps(context) {

/*
inside this getNode function I check for the content type and select the function to get the data for example 
getResourceTypeFromContext(context);
or getResourceFromContext( ...params )
*/

  const node = await getNode(context);


  if(node?.notFound){
    return ({
      notFound:true
    })
  }

  return ({
    props: {
      node
    },
    revalidate: 10,
  })
 
}

/* as for the paths I have */

export async function getStaticPaths(context) {
 /*empty for now due to high volume of nodes*/
  const type = [ ]

  const paths = await getPathsFromContext(type, context, {
    params: {
      "filter[status]": "1",
    }
  }).catch((error)=>{
    console.log('failed getPathsFromContext');
    return [];
  })

  return {
    paths: paths,
    fallback: 'blocking'
  }
}

```

**Comment by shadcn** [comment] 2022-06-21 07:56
@je34429 I'm marking this as completed following the comment here: https://github.com/chapter-three/next-drupal/issues/178#issuecomment-1118537941. Feel free to reopen if not. Thank you.

**Closed by shadcn** 2022-06-21 07:56 UTC
