### ISSUE TITLE
Starter does not build because of Type error

### ISSUE THREAD

**Issue by iamfredrik** [chapter-three/next-drupal#245] opened 2022-06-30 03:41 UTC
I can't get the starter to build. I tried creating a new project with the starter and without doing any modifications and the same problem persists. There is no problem running 'npm run dev', but when adding "build": "next build" to the scripts section in package.json and running 'npm run build', I get the following error:

> ./pages/api/revalidate.ts:21:40
> Type error: Expected 0 arguments, but got 1.
> 
>   19 | 
>   20 |   try {
> > 21 |     await response.unstable_revalidate(slug)
>      |                                        ^
>   22 | 
>   23 |     return response.json({})
>   24 |   } catch (error) {
> 
> > Build error occurred

Adding the following to next.config.js inside module.exports allows the project to build, but it's not the right way to solve this problem:

typescript: {
    ignoreBuildErrors: true,
 },

Would appreciate it if someone could take a look at this as I have no experience with TypeScript.

**Comment by shadcn** [comment] 2022-06-30 08:05
Let me try and reproduce this. I'm guessing `unstable_revalidate` has been updated in the latest `next`release. Looking.

Note: I've also published a quick guide here on how to can run the headless umami demo on your local. See https://gist.github.com/shadcn/23d2cff86eb68836774f877a3ecc88a3

**Comment by shadcn** [comment] 2022-06-30 08:07
@iamfredrik which next version is in your `package.json`?

**Comment by shadcn** [comment] 2022-06-30 08:17
Hmm I can't reproduce it with `npm` either. Can you try the following?

1. Delete the `node_modules` dir and`package-lock.json`.
2. Lock the `next` version to `12.1.4`

```diff
"dependencies": {
    "@tailwindcss/typography": "^0.5.2",
-    "next": "^12.1.4",
+   "next": "12.1.4",
    "next-drupal": "^1.4.0-rc.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
``` 

3. Run `npm install`
4. Then run `npm build` again.

Thank you

**Comment by iamfredrik** [comment] 2022-06-30 08:24
That seems to have done the trick. Thanks!

**Comment by shadcn** [comment] 2022-06-30 08:26
Nice. Probably the next 12.2 upgrade. We're still working on upgrading next-drupal to 12.2.

**Comment by shadcn** [comment] 2022-07-03 17:27
@iamfredrik Marking this as fixed. Feel free to reopen if not. Thank you.

**Closed by shadcn** 2022-07-03 17:27 UTC
