### ISSUE TITLE
Invalidate local task caches when a Next.js entity type is delete

### ISSUE THREAD

**Issue by mglaman** [chapter-three/next-drupal#480] opened 2023-04-21 15:47 UTC
If you go to /admin/config/services/next/entity-types and delete an entity, nodes still show Preview tab. Site WSOD. Invalidate local task plugin cache on delete.

Actually, it just always shows even if not configured. So there is a bigger bug here.

**Comment by apmsooner** [comment] 2023-04-21 16:55
The website encountered an unexpected error. Please try again later.
Error: Call to a member function getSitesForEntity() on null in Drupal\next\Render\MainContent\HtmlRenderer->prepare() (line 115 of modules/contrib/next/src/Render/MainContent/HtmlRenderer.php).

This would fix it:
`$resolver = $next_entity_type_config->getSiteResolver();
if (empty($resolver)) {
  return $build;
}

$sites = $resolver->getSitesForEntity($entity);
if (!count($sites)) {
  return $build;
}`

**Comment by apmsooner** [comment] 2023-04-21 16:59
FYI, i would have opened an issue on module page and submitted a patch but it seems they want to handle everything here outside of drupal. I'm not really sure how that fits into normal drupal issues or workflow.

**Comment by shadcn** [comment] 2023-04-21 17:01
@mglaman I'll look into it.

@apmsooner You can submit a PR here. I'll merge and credit you on d.o.

**Comment by JohnAlbin** [comment] 2024-02-22 14:43
Duplicate of #517

**Closed by JohnAlbin** 2024-02-22 14:43 UTC
